sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools # to get the new `repository-11.xml`
  - tools # to install Android SDK tools 25.1.x
  - platform-tools
  - build-tools-25
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24
  - extra-android-support
  - add-on
  - extra
branches:
  only:
  - master
  - develop
  - /^release/.*$/
  - /^hotfix/.*$/
script: "./gradlew ciBuild"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
  slack:
    rooms:
      secure: kbTANWggnsy0VZtCGk+l2chnnj5nXRqmOg4hZttDMLNCpVL0EyypbgPUn8sD3L0PvSRXdBBlv6UAbYe+Ld6XzG78c4opmSczs3F3Ps6SrTNWHGAXbF7lO74kGXKsMpDnhQy3kJRfLt+WQLTuBOeMNkTCPZJ92zLx4m9ER0miUQAVCl5g8AOxQu4IWZtoxBstDbPpc7otXvOqrADg2uoEZYrMjNOYKkLQrecNlbv81103v8oc0PEzTXlJTVUu22w74AwUe5k4LkrKEgvdHQJOAX/8KZpD5oaC/h3hPf/XQ16Jq434PKZ+DM6F/v/teGohJmtG7RpTcRoINe4viHlIDMCQT/3FZe919tIrKI5q9laISvWlVNCvNQNvnD1tLKvEqJbyL4asZn8MqscMDpu3msh+XRuhpOWGtsGQ1t4jCgHADWZQOf018XuqM/BMWoiVOKFYtEueHxFmuWCRBn1vu+tRNLnsbgZPRaZq7JnzbPUWaKHRKntG2HuT4p/RE060XjV8rdTeiX8Gq3LlfM/S8lZaOgJCjMM/ucr2Sx/J/cCg1VBuR8XbRXOsSOWrKVvaZBchZtfDXMCyKsLukkJipbCcs7EUqJUgIgb73HJmmESyMxsGd5adajNvE2jSiwpv7YyWiTC+gOzVvXDgNVxslMOy9rXhmJryJ4taBSXpEsI=
after_failure: "cat /home/travis/build/door2door-io/mobile-analytics-android/lib/build/outputs/lint-results-debug.xml"